### ISSUE TITLE
AdGuard stopped working on KakaoTalk ver. 4.0.0.3873

### ISSUE THREAD

**Issue by dongmin-dev** [loopback-kr/KakaoTalkADGuard#1]
Current environment:
OS: Windows 11 23H2
KakaoTalk: 4.0.0.3873
AdGuard: 1.0.0.3

KakaoTalkADGuard can't block ADs on this version.
I'm adding a screenshot of my screen.

Thanks!

![screenshot](https://github.com/loopback-kr/KakaoTalkADGuard/assets/63569586/56b63fe1-792c-4b3d-bb4b-dcdb0e247c93)

**Comment by loopback-kr** [comment]
Thank you for your feedback, I will check the problem!
I recommend that you do not use AD Guard until this issue is resolved.

**Comment by loopback-kr** [comment]
I just pushed a hotfix. There is additional limitation (refer to README.md), but it will works experimentally.
Thanks again. 😊

**Comment by dongmin-dev** [comment]
Thank you for the fast update!
Will try it out rn 👍

**Comment by dongmin-dev** [comment]
Tried the new version and works flawlessly!
Hope to see fixes in future updates
Thank you for your hard work 💪

**Comment by loopback-kr** [comment]
@ssoaora Fixed a limitation that existed in version 1.0.0.4. Please try version 1.0.0.6. (●'◡'●)

**Comment by dongmin-dev** [comment]
@loopback-kr Thanks!
But there's another bug on 1.0.0.6.
This bug shows a white square in the advert area in lockdown mode.
The square does not disappear even if I move/resize the window.

+) Everything works fine except for that bug.

Also adding a screenshot of this bug too.
![screenshot](https://github.com/loopback-kr/KakaoTalkADGuard/assets/63569586/e8e679ef-99fb-4f23-a764-a0f59c361555)

**Comment by loopback-kr** [comment]
Thanks, I'll check it! ✔

**Comment by loopback-kr** [comment]
I have fixed the issue. Thank you for letting me know. 👍 Try version 1.0.0.8

**Comment by dongmin-dev** [comment]
Adguard is now perfect with no bugs!
Thanks again.

Closing issue
