### ISSUE TITLE
kakaotalk goes vibrating

### ISSUE THREAD

**Issue by ydungwoo** [loopback-kr/KakaoTalkADGuard#2]
![Honeycam 2024-04-21 16-10-23](https://github.com/loopback-kr/KakaoTalkADGuard/assets/51860157/0ad71f5f-1523-4669-8320-e64332b6078c)

it is shaking!

windows ver 4.0.0.3873

**Comment by loopback-kr** [comment]
This didn't happen in my environment, but it can happen if you're running more than one KakaoTalk AD blocker. Please try closing other AD blockers and then test version 1.0.0.6.

**Comment by ydungwoo** [comment]
It works!
