### ISSUE TITLE
It doesn't work on the new version

### ISSUE THREAD

**Issue by a24505688** [loopback-kr/KakaoTalkADGuard#3]
kakaotalk version: 4.0.0.3881
Adguard version : 1.0.0.6
Windows version : Win11 23H2 22631.3447
![image](https://github.com/loopback-kr/KakaoTalkADGuard/assets/168133187/ef072d3f-03b7-45cf-a059-fb4f336b5bb3)
After the KakaoTalk update, it seems like the pop-up ads are not appearing, but the bottom ads keep showing up. Sometimes the ads flicker and disappear, but then they reappear

**Comment by loopback-kr** [comment]
As you know, if the KakaoTalk process has administrator privileges, AD blocking is not possible unless AD Guard is also promoted (refer to README.md). Except in this case, it did not reproduce in my environment. Can you check again if the process is promoted to administrator rights or not?

![preview](https://github.com/loopback-kr/KakaoTalkADGuard/assets/28856527/9a807fe2-c78b-4de0-8d3f-81e15dceb2fc)

**Comment by a24505688** [comment]
![k1](https://github.com/loopback-kr/KakaoTalkADGuard/assets/168133187/b88de7a6-6319-4f3f-9375-10e4fc1ef4df)
I've checked it.
I've granted administrator access to both KakaoTalk and AdGuard, and even with AdGuard alone, the same issue persists.

**Comment by loopback-kr** [comment]
I've released beta 1 and 2 versions that fix the suspected cause, please test both versions.

The applications each users are using vary too much to reproduce this bug in my testbed environment.
If the files can't resolve the bug and you don't mind, can you provide a list of processes that are running in the state you are currently experiencing the issue(AD Guard is running but failing to block ADs)?

Run `Get-CimInstance Win32_Process | Select Name,CommandLine > KakaoTalkADGuard-ProcDump.dbg` in Windows Powershell
Send the file (`KakaoTalkADGuard-ProcDump.dbg`) to [hyunseoki@outlook.kr](mailto:hyunseoki@outlook.kr)

Thank you!

**Comment by a24505688** [comment]
I've sent the file.
After installing beta1 version, the ads are removed properly.
However, in beta2 version, ads are still being displayed.
Thank you.

**Comment by loopback-kr** [comment]
Changed banner AD blocking conditions in 1.0.0.7. Please check if it works.

**Comment by a24505688** [comment]
I installed and checked the new version, and it's working fine without any issues. Thank you.
