### ISSUE TITLE
업데이트한 프로필 안보여요

### ISSUE THREAD

**Issue by rulekak** [loopback-kr/KakaoTalkADGuard#4]
## 버그 설명
*구체적으로 버그에 대해 설명해 주세요.*

업데이트한 프로필이 안보입니다.
이전버전에서는 문제가 없었는데 
현버전에서는 업데이트한 프로필이
![K-001](https://github.com/loopback-kr/KakaoTalkAdGuard/assets/90678061/e6253b96-722c-490c-9c9d-530a415562a0)
이런식으로 나옵니다.

**Comment by loopback-kr** [comment]
알려주셔서 감사합니다. 빠른 시일 내에 수정하겠습니다. 감사합니다!

**Comment by loopback-kr** [comment]
1.0.0.9 버전에서 테스트해보세요! 감사합니다.

**Comment by rulekak** [comment]
> 1.0.0.9 버전에서 테스트해보세요! 감사합니다.

확인결과 잘되네요 :D 감사합니다!!!!! 고맙습니다!
