### ISSUE TITLE
창 열림 버그

### ISSUE THREAD

**Issue by zulex1** [loopback-kr/KakaoTalkADGuard#5]
카톡 알림이 올 때 갑자기 카톡 창이 화면에 뜨는 버그가 있는것 같습니다.

**Comment by loopback-kr** [comment]
안녕하세요.

정확한 재현 과정을 찾기 어려워 문제 원인을 파악하지 못하고 있어 추가적인 정보를 요청드립니다.
카카오톡 알림창(알림이 올 때 우측 하단에 알림창이 나타나는) 옵션을 사용하고 계시나요?
카카오톡 메인창을 단순히 최소화 한 상태인가요? 메인창을 닫고 트레이아이콘만 남은 상태인가요?
문제 재현이 되는 상황을 녹화한 영상이 있으면 원인 파악에 큰 도움이 될 것 같습니다.

알림창이 나타나고 있는 순간에 카카오톡 메인창을 열면 광고가 차단되지 않는 문제가 확인되었으나, 카카오톡 알림이 올 때 닫혀있던 카카오톡 메인 창이 갑자기 열리는 상황은 재현되지 않고 있습니다.

알려주셔서 감사합니다!

**Comment by loopback-kr** [comment]
1.0.0.10 버전에도 동일하게 증상이 나타나는지 확인 요청드립니다. 감사합니다!

**Comment by zulex1** [comment]
> 안녕하세요.
> 
> 정확한 재현 과정을 찾기 어려워 문제 원인을 파악하지 못하고 있어 추가적인 정보를 요청드립니다. 카카오톡 알림창(알림이 올 때 우측 하단에 알림창이 나타나는) 옵션을 사용하고 계시나요? (네) 카카오톡 메인창을 단순히 최소화 한 상태인가요? (네, 그런데 저는 듀얼 카톡 / 듀얼 카톡 애드가드 사용 중입니다. 듀얼 카톡은 Sandboxie 이용) 메인창을 닫고 트레이아이콘만 남은 상태인가요? (네 메인창, 서브창 닫고 hide 기능으로 아이콘 꺼 놓은 상태입니다.) 문제 재현이 되는 상황을 녹화한 영상이 있으면 원인 파악에 큰 도움이 될 것 같습니다. (다른 이유가 있는거 같아서 지켜보고 계속 그러면 녹화해 보겠습니다. 이게 갑자기 한두번씩 그러는거라서 캡쳐가 쉽지 않을 수도 있어요.)
> 
> 알림창이 나타나고 있는 순간에 카카오톡 메인창을 열면 광고가 차단되지 않는 문제가 확인되었으나, 카카오톡 알림이 올 때 닫혀있던 카카오톡 메인 창이 갑자기 열리는 상황은 재현되지 않고 있습니다. (네 답변 감사합니다. 한가지 제안은 기본 아이콘이 안 이쁜거 같아요 ㅠㅠ 그래서 제가 무료 아이콘 다운받아서 바꾸어서 사용 중입니다.  제가 사용 중인 아이콘 첨부합니다. 좋은 프로그램 제공해 주셔서 감사해요. 최애 프로그램 중 하나입니다.)
> 
![kakotalk adguard capture](https://github.com/loopback-kr/KakaoTalkAdGuard/assets/112995566/004e644e-6878-49d1-b191-97362837b221)

> 알려주셔서 감사합니다!

안녕하세요.

회사하고 집에서 동시 사용 중인데 회사에서만 그러는거 보니 다른 원인이 있을 수도 있어서 몇일 더 지켜보려고 합니다.
