### ISSUE TITLE
오늘 카카오톡이 업데이트 되었는데 광고가 다시 나오는 것 같습니다. (4.3.0.4263)

### ISSUE THREAD

**Issue by zulex1** [loopback-kr/KakaoTalkADGuard#6]
## 버그 설명
*구체적으로 버그에 대해 설명해 주세요.*

## 재현
*버그 재현을 위한 절차:*

*1. '...'로 이동.*

*2. '....'을 클릭.*

*3. '....'으로 스크롤*

*4. '...' 오류 발생*

## 시스템 환경
*버그가 발생하는 시스템 환경을 명시해 주세요.*

 - Windows 버전: ??.?.?????.????
 - OS 로케일:
    - [x] 한국어
    - [ ] 영어
    - [ ] 그 외: 
 - OS 아키텍처:
    - [ ] x86 (32-비트)
    - [x] x64 (64-비트)
 - 카카오톡 버전: ?.?.?.????
 - 관리자 권한을 가진 카카오톡 프로세스
    - [ ] 예
    - [x] 아니오
 - AdGuard 버전: ?.?.?.?
 - 관리자 권한을 가진 AdGuard 프로세스
    - [ ] 예
    - [x] 아니오

## 스크린샷
*가능하다면, 문제를 설명하기 위한 스크린샷을 추가해주세요.*

## 추가 참고 사항
*문제에 대한 추가적인 설명을 기술해 주세요.*

**Comment by loopback-kr** [comment]
1.0.0.11 버전에서 해당 문제를 해결하였습니다. 알려주셔서 감사합니다!

**Comment by zulex1** [comment]
빠른 처리 감사합니다!
